### ISSUE TITLE
Repo code not working on sample data

### ISSUE THREAD

**Issue by psycoplankton** [Priya22/EmotionDynamics#3]
I am trying to run the code on the dataset given in the repo in the `sample_data` folder but its throwing an error. 
```python
Step 2: computing UED metrics
Traceback (most recent call last):
  File "/Users/vanshgupta/Desktop/ntu/EmotionDynamics/code/uedLib/lib/ued.py", line 388, in <module>
    main(args.config, args.post_process, args.pre_process)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanshgupta/Desktop/ntu/EmotionDynamics/code/uedLib/lib/ued.py", line 364, in main
    res_dict = ued(config, df)
  File "/Users/vanshgupta/Desktop/ntu/EmotionDynamics/code/uedLib/lib/ued.py", line 144, in ued
    emoverbose, emosummary = process_dimension(tdf, lex, edim, config)
                             ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanshgupta/Desktop/ntu/EmotionDynamics/code/uedLib/lib/ued.py", line 199, in process_dimension
    emoverbose, emosummary = line_analysis(emoData, config, edim)
                             ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanshgupta/Desktop/ntu/EmotionDynamics/code/uedLib/lib/ued.py", line 214, in line_analysis
    data = data.groupby(idCol).apply(utils.displacement_number)
           ~~~~~~~~~~~~^^^^^^^
  File "/Users/vanshgupta/opt/anaconda3/envs/emody/lib/python3.13/site-packages/pandas/core/frame.py", line 9183, in groupby
    return DataFrameGroupBy(
        obj=self,
    ...<7 lines>...
        dropna=dropna,
    )
  File "/Users/vanshgupta/opt/anaconda3/envs/emody/lib/python3.13/site-packages/pandas/core/groupby/groupby.py", line 1329, in __init__
    grouper, exclusions, obj = get_grouper(
                               ~~~~~~~~~~~^
        obj,
        ^^^^
    ...<5 lines>...
        dropna=self.dropna,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/vanshgupta/opt/anaconda3/envs/emody/lib/python3.13/site-packages/pandas/core/groupby/grouper.py", line 1033, in get_grouper
    obj._check_label_or_level_ambiguity(gpr, axis=axis)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/vanshgupta/opt/anaconda3/envs/emody/lib/python3.13/site-packages/pandas/core/generic.py", line 1868, in _check_label_or_level_ambiguity
    raise ValueError(msg)
ValueError: 'idCol' is both an index level and a column label, which is ambiguous.
``` 

It is being caused by the line 214 in the ued.py file.
```python
data = data.groupby(idCol).apply(utils.displacement_number)
```

The config file is as follows:
`
iden: bookSpeakers
data_path: sample_data/sample_input.csv
disp_length_min: 1
emoCols:
- valence
- arousal
- dominance
filter: true
idCol:
- speaker
- novel
level: 0.68
lex_path: lexicons/NRC-VAD-Lexicon.csv
min_tokens: 5
min_turns: 1
rollingWindow: 5
save_dir: sample_data/speaker_outputs/
stopword_path: lexicons/stopwords.txt
stopwords: true
textCol: text
timeCol: narrativeTime
textIdCol: dialogueTurn
hb_type: SPK100
compress: False`

Can anyone tell me what the issue is?. 
I am using python 3.12 for running it.

**Comment by dexterwilliams96** [comment]
Did you ever resolve this? I'm running into the same issue

**Comment by wuhongyan123** [comment]
Hi, I'm having the same issue. Did you manage to resolve it?
